apiVersion: v1
kind: Service
metadata:
  name: sign-language-api
spec:
  selector:
    app: sign-language-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Gets a public IP